version: "3.4"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  keycloak:
    image: jboss/keycloak:9.0.0
    restart: on-failure
    volumes:
      - ./keycloak.cli:/opt/jboss/startup-scripts/keycloak.cli
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
      - PROXY_ADDRESS_FORWARDING=true
    depends_on:
      - keycloak-db
    ports:
      - "8027:8080"

  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  keycloak.cli:
